[build-system]
requires = ["setuptools>=67.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "FlaskVerse"
version = "1.0.0"
dependencies = [
    "Flask",
    "flask-smorest",
    "toml"
]

