API_TITLE = "FlaskVerse"
API_VERSION = "v1"
OPENAPI_VERSION = "3.0.2"
OPENAPI_SWAGGER_UI_URL = "https://cdn.jsdelivr.net/npm/swagger-ui-dist/"
OPENAPI_URL_PREFIX = "/"
OPENAPI_SWAGGER_UI_PATH = "/swagger-ui"
OPENAPI_SWAGGER_UI_VERSION = '3.23.5'
